sudo: required

services:
  - docker

before_install:
- docker pull wolf3d/palmos.sdk.3.1

script:
- docker run -it -v $(pwd):/root/neko-for-pilot wolf3d/palmos.sdk.3.1 /bin/sh -c "cd /root/neko-for-pilot/neko/src && ls -rtal"
